// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_draft from "./routes/api/draft.ts";
import * as $api_publish from "./routes/api/publish.ts";
import * as $index from "./routes/index.tsx";
import * as $AdminForm from "./islands/AdminForm.tsx";
import * as $CommandList from "./islands/CommandList.tsx";
import * as $Editor from "./islands/Editor.tsx";
import * as $EditorShell from "./islands/EditorShell.tsx";
import * as $ImageUploadNodeView from "./islands/ImageUploadNodeView.tsx";
import * as $extensions_ImageUploadNode from "./islands/extensions/ImageUploadNode.tsx";
import * as $extensions_SlashCommand from "./islands/extensions/SlashCommand.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/draft.ts": $api_draft,
    "./routes/api/publish.ts": $api_publish,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AdminForm.tsx": $AdminForm,
    "./islands/CommandList.tsx": $CommandList,
    "./islands/Editor.tsx": $Editor,
    "./islands/EditorShell.tsx": $EditorShell,
    "./islands/ImageUploadNodeView.tsx": $ImageUploadNodeView,
    "./islands/extensions/ImageUploadNode.tsx": $extensions_ImageUploadNode,
    "./islands/extensions/SlashCommand.ts": $extensions_SlashCommand,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
